name: 2 - Auto approve PRs
on:
  pull_request:
    branches: ["master"]
    types: ["opened"]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: andrewmusgrave/automatic-pull-request-review@0.0.2
        if: startsWith(github.head_ref, 'auto/pr-')
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          event: APPROVE
          body: Approving automated PR
