# name of workflow
name: test workflow
# event that will trigger the workflow
on:
  pull_request: 
    types: [ opened,reopened ]

# jobs
jobs:
  approver:
    
     name: Approve and Auto merge
     runs-on: ubuntu-latest
     steps:
      
       - uses: hmarr/auto-approve-action@v2.0.0
         if: github.actor == 'zachydev' || github.actor == 'dependent-preview[bot]'
         with:
           github-token: "${{ secrets.GITHUB_TOKEN}}" 
       - name: Finishing up and approving PR
         run: echo approved pr
  merger:
    
    if: github.actor == 'zachydev'
    name: waiting to merger pr
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v1
    
    - uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Pull Request Merginator
      uses: managedkaos/merge-pull-request@v1.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
